### ISSUE TITLE
Units: targeting: add pre-defined topics, such as "crypto", "adult", "stremio", etc.

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-platform#107]
predefined topics to choose from

**Comment by vanina-iv** [comment]
These are the old interest/affinity categories: https://docs.google.com/spreadsheets/d/1XD2lQxxyiXM_7iIGLgYqC_vtYuVHSnalHC9JFJViNB4/edit#gid=1438556343 (they were created for behavioral targeting)

I'm working on a new list that works with contextual targeting.

**Comment by rori4** [comment]
When working on google vision (#40) categories I needed to use were those categories -> [https://cloud.google.com/natural-language/docs/categories](https://cloud.google.com/natural-language/docs/categories)

**Comment by Ivshti** [comment]
This was done a long time ago.

Closing - any continuous effort is related to #297
