### ISSUE TITLE
Bannersnack integration 

### ISSUE THREAD

**Issue by dmngdsm** [AdExNetwork/adex-platform#115]
## Overview

Integrate Bannersnack - a Canva-like platfrom for banners creation. They are open for integration w. AdEx, it will be free of charge and without any terms. AdEx advertisers will have to pay for banners created through Bannersnack - $4 per banner, we can add overhead too (f.e. competitor Match2One offers the banners for $5).

This is the  [developers' documentation](https://docs.enterprise.bannersnack.com/getting-started/) .

**Comment by Ivshti** [comment]
it will be a while until we get to this; but it's a very nice thing to have

**Comment by dmngdsm** [comment]
> it will be a while until we get to this; but it's a very nice thing to have

For sure, it's just good to know it's there

**Comment by Ivshti** [comment]
removing the tag gitcoin-candidate cause this might require active communication with bannersnack

**Comment by dmngdsm** [comment]
This one - I'm closing it for now, but we may keep it in mind for future development
