### ISSUE TITLE
use js/IdentityProxyDeploy for generating proxy addresses

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-platform#130]
use that library on the client side to predict the identity address, rather than getting it from the backend

**Comment by IvoPaunov** [comment]
https://github.com/AdExNetwork/adex-protocol-eth/compare/solc-wrapper?expand=1

it works but is ugly as ****. It's better than adding the browser compiled solc code in the repo. May need to export the version/link to it as cfg or something
