### ISSUE TITLE
Drop words "voucher" and "grant" for "invite"

### ISSUE THREAD

**Issue by dmngdsm** [AdExNetwork/adex-platform#148]
I suggest that we call the codes we sent to advertisers and publishers: "invitation codes" or "invite codes" since it is much more common wording. 

Right now we are saying grant codes (although there are no grants for publishers) and on the registering window on the platform we say "voucher" which sounds bad(the last one is personal opinion).

Why not always use "invitation code", when there is a grant it will be "invitation code with XX DAI grant" or sth like that.

**Comment by Ivshti** [comment]
:+1:

**Comment by vanina-iv** [comment]
Futile effort, we're opening the platform to the general public soon.

**Comment by Ivshti** [comment]
yeah, I'll close since the estimation for public signups is a week or so; other than that, it's a good point
