### ISSUE TITLE
Don't show errro messages when there is nothing in fields

### ISSUE THREAD

**Issue by TRtomasz** [AdExNetwork/adex-platform#154]
**Description**
Error messages are still displayed even when there is nothing in the fields. No one like red warning messages, we should hide them after user has cleared the content.
**Screenshots**
![image](https://user-images.githubusercontent.com/40594253/66122271-90201480-e5df-11e9-8541-d568b31c240a.png)

**Comment by IvoPaunov** [comment]
If the field was dirty it will be red.
