### ISSUE TITLE
Undefined granted amount after registration

### ISSUE THREAD

**Issue by TRtomasz** [AdExNetwork/adex-platform#155]
**Description**
Registration field that granted amount is `undefined` as you can see on the screenshots
**Screenshots**
![image](https://user-images.githubusercontent.com/40594253/66122362-c9588480-e5df-11e9-9317-67376937bb21.png)

**Comment by rori4** [comment]
I have investigated this and I can see that the relayer doesn't send back granted amount.

**Comment by Ivshti** [comment]
No longer relevant - this system is now obsolete
