### ISSUE TITLE
HTTP 504 & 520 Errors on tom.moonicorn.network/.../last-approved

### ISSUE THREAD

**Issue by TheBoroer** [AdExNetwork/adex-platform#170]
`https://tom.moonicorn.network/channel/......../last-approved` gives 504 and 520 errors causing certain UI functions to break.

I get an error message at the bottom of the screen: `Error getting stats: TypeError: Failed to fetch`

**Comment by Ivshti** [comment]
fixed shortly after the issue, but forgot to close this
