### ISSUE TITLE
After you connect with Metamask if you log out the app crashes

### ISSUE THREAD

**Issue by rori4** [AdExNetwork/adex-platform#179]
### Summary
There is an bug that causes the application to crash when you try to login with Metamask and during the stepping process you logout of Metamask and click continue

### Expected Behavior
When you logout from Metamask you should be redirected to the homepage

### Actual Behavior
Nothing happens. You are able to click Continue 

### Steps to Reproduce the Problem

  1. Start the process of logging in with Metamask
  2. Connect your Metamask 
  3. Logout of Metamask
  4. Click "Continue"

### Specifications

  - Browser: Chrome Version 77.0.3865.90
  - OS: Ubuntu 18.04.3 LTS
  - Login Method: Metamask

### Screenshots
![errorLogout](https://user-images.githubusercontent.com/22402693/66752020-19193480-ee99-11e9-96c7-850eb6fdba06.png)

**Comment by IvoPaunov** [comment]
Please,  don't change anything. I know about this and I think it's fixed in
counterfactual-accounts branch.

**Comment by rori4** [comment]
I have checked your solution but I found another issue with it. You can sign and login with an account that has no privileges attached in the Metamask with an account that has privileges.
I think that we should just redirect to homepage after account change and logout so we can hide and reset the login form.

**Comment by IvoPaunov** [comment]
I has to reset the account on metamask account chage. If it doesn't it is
not merged from master or it's a bug. I'll check it.

**Comment by rori4** [comment]
It resets the account but the Login dialog stays and you can click continue. I believe the page should be redirected with history.push('/'). I have made a fix for that that does not conflict with your code in counterfactual-accounts and we can discuss it when you return.

**Comment by IvoPaunov** [comment]
Ok
