### ISSUE TITLE
Issues with tag selection when creating ad slots

### ISSUE THREAD

**Issue by TRtomasz** [AdExNetwork/adex-platform#191]
**Describe the bug**
It is not possible to change slot without clearing the field with backspace
It is possible to create ad slot with more then one tag using the same category

**To Reproduce**
1. Create new ad_uni
2. When tag is selected clicking again on that field doesn't show tags list so you have to clear field with backspace and then it will be displayed
3. It is possible to select the same tag category for next tags

**Expected behavior**
It should be possible to change tag when it is selected without need to clear the field
It shouldn't be possible to creat ad slot with more then one instance of the same tag category

**Screenshots**
https://slack-files.com/T08Q9N48G-FPAUS71S7-2f4f282c63

**Desktop (please complete the following information):**
Firefox 69.0.3 Windows 10

**Comment by rori4** [comment]
Yes I have created the same issue like this one an hour ago #190
