### ISSUE TITLE
When session is stored then every button redirects to the platform side choosing view

### ISSUE THREAD

**Issue by TRtomasz** [AdExNetwork/adex-platform#194]
**Describe the bug**
When we open https://platform.adex.network/#/ and user session is stored in saved. Then clicking on any of the buttons redirects to the side choosing view(advertiser/publisher). I have checked it only with grant account.

**To Reproduce**
1. Go to adex platform, log in using grant account
2. Close webpage
3. Go to the adex platform, click any button: metamask, trezor, create grant account
4. Instead of possibility to create/login using different account you are redirected to the side choosing view again

**Expected behavior**
1. When user session is stored and he goes to the adex platform mainpage he should be redirected to the side choosing view
OR
2. When user session is stored and we don't want to redirect him to side the choosing view immediately:
Clicking on "Login Grant Account" should redirect to the side choosing view
Clicking on any other button should let user to log in using new account. Perhaps there could be a warning message about another account being logged in.

**Screenshots**
![image](https://user-images.githubusercontent.com/40594253/67465144-e8798d80-f644-11e9-9543-b376406b766e.png)

**Desktop (please complete the following information):**
Windows 10 Firefox 69.0.9

**Comment by IvoPaunov** [comment]
I know about that issue,  I have idea for quick fix but it might not work.
