### ISSUE TITLE
Integrate a live chat widget

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-platform#196]
**Is your feature request related to a problem? Please describe.**
New users are often confused about certain aspects of the platform. Because the UX is not especially polished right now, the platform has a lot of rough edges.

Adding a chat widget would enable us to help users, as well as identify rought edges and solve them

**Describe the solution you'd like**
Integrate a FB messanger live chat (or other, ask @dmngdsm and @vanina-iv) widget 

**Describe alternatives you've considered**
All of the chat widgets

**Additional context**

**Comment by dmngdsm** [comment]
FB is a bad idea for this kind of chat. I recommend sth. like Zendesk (if we use for support tickets too) or Drift (I've used it and I'm pretty happy with it).

**Comment by rori4** [comment]
How about [Tidio](https://www.tidio.com/). I have used it before and is quite good. Also free for lifetime for up to 3 users

**Comment by dmngdsm** [comment]
Why not, if you have integrated it before and are happy with it. Let me just see how it stands up against the other two in terms of functionalities.
