### ISSUE TITLE
 Differentiate MetaMask from other ethereum-compatible browsers

### ISSUE THREAD

**Issue by IvoPaunov** [AdExNetwork/adex-platform#204]
We have to stop using `metamask` as it only way `ethereum` is injected.
Need to [detect ](https://metamask.github.io/metamask-docs/Main_Concepts/Getting_Started#detecting-metamask)if the browser itself injects `ethereum` and not show it as `metamask`
That is time consuming task and may lead to some unexpected issues.

**Comment by Ivshti** [comment]
Pretty sure this is sort of done or irrelevant, as the way web3 is injected was changed a couple of time since 2019
