### ISSUE TITLE
logins buttons suddenly resize themselves

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-platform#206]
**Describe the bug**
on the home screen, the login buttons suddenly resize themselves and become less wide, leaving more gap to the right

might be related to the recently added chat

**To Reproduce**
just go to the login screen

**Comment by rori4** [comment]
I can't reproduce this issue on v.4.1.22-beta

**Comment by rori4** [comment]
I was able to reproduce it on Opera Version:64.0.3417.92
