### ISSUE TITLE
Campaign statistics: spend breakdown

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-platform#211]
**Is your feature request related to a problem? Please describe.**
There's no way to figure out where the campaign funds were spent right now, other than the publisher eth addresses, which is not really useful

**Describe the solution you'd like**
A breakdown of campaign spend by hostname. To achieve this, ad slots will have to be tied to hostnames, or the hostname will be separately recorded by the validator.

Ideally in the future you'd able to see the average targeting match too (not sure about this - since it might create privacy problems)

**Describe alternatives you've considered**
Could be a breakdown of publishers by their ENS username, once we [implement those](#29)

**Additional context**
Depends on changes in the validator (eventStats), so it's blocked for now

**Comment by alesinka** [comment]
Can we use both table and a piechart? Also the idea is the piechart to be interactive somehow, when hover on certain color to show a tooltip with info: 
![Campaign stats](https://user-images.githubusercontent.com/24762344/72254795-c07b4400-360d-11ea-8859-2a726ccb19f4.jpg)

**Comment by Ivshti** [comment]
No longer blocked by validator, as the advanced reports got merged: https://tom.adex.network/analytics/advanced?eventType=IMPRESSION (requires proper bearer auth)
