### ISSUE TITLE
DAI Balance doesn't get updated unless you refresh

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-platform#221]
**Describe the bug**
the DAI balance stays the same for a while after it's actually updated on-chain; of course, channel balance should be updated too

**To Reproduce**
1. See your DAI balance
2. send yourself some DAI
3. click through the UI; doesn't get updated

**Expected behavior**
To update it frequently

**Additional context**
Possible solutions

1. use ethers to connect via websocket to the node and watch for changes
2. just run the update procedure every 10-15 seconds (seems better/easier)

**Comment by IvoPaunov** [comment]
fixed in https://github.com/AdExNetwork/adex-platform - no PR yet - just deployed in staging
