### ISSUE TITLE
visual: DAI balance is hidden by "New campaign button"

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-platform#222]
**Describe the bug**
DAI balance partially covered by a button

**To Reproduce**
1. Go to Campaigns
2. see your DAI balance in the upper right

**Expected behavior**
The balance should be displayed more towards the upper part of the screen

**Screenshots**
![Screenshot_2019-11-04 AdEx Platform(1)](https://user-images.githubusercontent.com/1247629/68119259-e9df6b80-ff0a-11e9-9ed9-f9e56769932b.png)

**Comment by IvoPaunov** [comment]
fixed in https://github.com/AdExNetwork/adex-platform - no PR yet - just deployed in staging
