### ISSUE TITLE
Change UTM links when name of ad unit is changed

### ISSUE THREAD

**Issue by dmngdsm** [AdExNetwork/adex-platform#223]
**Is your feature request related to a problem? Please describe.**
If a user wants to change ad unit name for some reason, but is already using UTM data for analytics with the old name, the UTM link should also change. Otherwise renaming Ad Units is close to meaningless.

**Describe the solution you'd like**
Possible solution: Just change UTM link when ad unit name is changed.

**Describe alternatives you've considered**
Alternative: "Create New From" button that copies an ad unit as new one, but with unsaved targeting and name, so that you can create an ad unit with a new name but no need to upload creative again. I actually like this solution even better.

**Additional context**
/

**Comment by dmngdsm** [comment]
@rori4  just showed me the "Cloning" feature which is 100% my alternative solution. Figure out if you want to however try the solution I first suggested, but I'm perfectly happy with the existing one too.

**Comment by rori4** [comment]
We can't update the UTM url right as this is by specification in the adex protocol. Here is the info about the AdUnit [https://github.com/AdExNetwork/adex-protocol/blob/master/campaignSpec.md#spec-properties-added-to-ipfs-and-can-not-be-modified](https://github.com/AdExNetwork/adex-protocol/blob/master/campaignSpec.md#spec-properties-added-to-ipfs-and-can-not-be-modified)

**Comment by Ivshti** [comment]
This is also blocked by principle/security. Should we allow overriding the URL? This can lead to scams.

So this must be accompanied by a change in the ad view that will accept the override if it ONLY changes the UTM

**Comment by rori4** [comment]
@Ivshti We have discussed this with @dmngdsm that cloning of the AdUnit solves the issue. If you want to change the UTM just clone it.

**Comment by Ivshti** [comment]
Then it's a security vulnerability that must be addressed in the adview

**Comment by IvoPaunov** [comment]
If you clone it it will not  replace the previous one and will not be
included in existing campaigns.

**Comment by dmngdsm** [comment]
It is fine, if you have a wrong ad unit that you wanted to rename, you would have to stop the campaign anyway.

Cloning is totally solving this problem for now, there's no need to waste time on it.
