### ISSUE TITLE
Campaign Statistics: Add cumulative spend/revenue 

### ISSUE THREAD

**Issue by dmngdsm** [AdExNetwork/adex-platform#231]
**Is your feature request related to a problem? Please describe.**
Publishers and advertisers should be able to see their aggregate spend/earnings and impressions for specific periods of time

**Describe the solution you'd like**
We have time-based charts on the dashboard. Add a cumulative spend/earn OR impressions (depending on what you're displaying, calculated by summing all datapoints) on top of it, and average CPM (weighted average). 

See added screens - A perfect reference is the Google Ads chart.
Calendar for dates pickup doesn't have to be that complex if it requires a lot of work
On top of the chart you can see Average CPM for the Period + number of impressions. At some point Clicks too.

**Additional context**
![Screenshot 2019-11-11 at 15 46 43](https://user-images.githubusercontent.com/15030734/68592103-f7609c80-049a-11ea-9353-0b26b3a10e3e.png)
![Screenshot 2019-11-11 at 15 49 40](https://user-images.githubusercontent.com/15030734/68592104-f7609c80-049a-11ea-90d3-d44fcfb16fe5.png)

**Comment by rori4** [comment]
I was working on this to make it with a calendar like this from google but this is blocked by the validator. Currently we receive from there the following:
Hourly -> Gets the last hour with minutes Interval
Daily -> Gets the last 24 hours with interval of an hour
Weekly -> Gets last 7 days with 6 hours inteval

If we don't change this in the validator we can't implement this.

**Comment by Ivshti** [comment]
we don't want the calendar thing, we just want an aggregate of what's shown in the chart

**Comment by rori4** [comment]
@Ivshti You mean this on top of the chart, right?
![aggregation](https://user-images.githubusercontent.com/22402693/68594232-cc2c7c00-049f-11ea-90aa-fbafa58ba37a.png)

**Comment by Ivshti** [comment]
yes
