### ISSUE TITLE
Platform Status Page

### ISSUE THREAD

**Issue by dmngdsm** [AdExNetwork/adex-platform#234]
**Is your feature request related to a problem? Please describe.**
When we go live it will be good to have a status page on the platform. It can also be used for notifications for updates, news, etc.

**Additional context**
[Revolut](https://www.revolut.com/system-status) is a good example

**Comment by vanina-iv** [comment]
Not sure this adds a lot of value to our users...

**Comment by Ivshti** [comment]
It sort of does, if we had a lot of users

I'm going to close this since we have no bandwidth for it and there's very little need for it currently
