### ISSUE TITLE
Upload adex account data does nothing

### ISSUE THREAD

**Issue by TRtomasz** [AdExNetwork/adex-platform#241]
**Describe the bug**
After uploading adex account data json file nothing happens.
**To Reproduce**
1. Go to platform.adex.network
2. Select option to login with grant account
3 Click option UPLOAD ADEX-ACCOUNT-DATA.json
4. Select a file
5. Upload it.

**Expected behavior**
For a valid file nothing happens, user is not logged in. 
For not valid file there is not user readable message about wront token in json it should be changed to more human readable 
**Screenshots**

**Desktop (please complete the following information):**
Windows 10, Firefox 70.0.1

**Smartphone (please complete the following information):**

**Additional context**
After uploading valid file there are new entries added to the local storage.

**Comment by IvoPaunov** [comment]
There are toast notifications when you upload valid or invalid file.

**Comment by IvoPaunov** [comment]
You can not log in wit file because it is encrypted with email and password

**Comment by Ivshti** [comment]
Not relevant anymore, with cloud-based quick accounts
