### ISSUE TITLE
Continue as <login> button should stay until next login is performed

### ISSUE THREAD

**Issue by TRtomasz** [AdExNetwork/adex-platform#242]
**Describe the bug**
There is new button added to restore previous session "Continue as ..." after, just, clicking another button continue button is gone it should stay until login with another account action is actually performed
**To Reproduce**
1.Open platfor.m.adex.network
2. Login in with a grant account
3. Close tab with adex platform
4. Open platform.adex.network
5. There is a new button "continue as..."
6. Click another button like "create new grant account"
7. "continue as .." button is gone

**Expected behavior**
If user was logged previously, option to continue with previous session should stay as long as another login action isn't performed. Another option is to show warning after clicking another button and clearing user data about what will happen to give him occasion to cancel the operation.
**Screenshots**

**Desktop (please complete the following information):**

Windows 10 Firefox 70.0.1

**Comment by rori4** [comment]
How about we redirect the user to /side-select if there are credentials present and ditch the button?I think its better @IvoPaunov
199e4ea

**Comment by IvoPaunov** [comment]
the redirect is not good idea. I'll fix it with confirmation dialog
