### ISSUE TITLE
When there is no data available for the chart display a placeholder

### ISSUE THREAD

**Issue by TRtomasz** [AdExNetwork/adex-platform#255]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When there is no data to be displayed on the chart there is no purpose to display the chart. Instead of it we could display messages <Create your first campaign> Or <Create your first ad slot> with links to the tutorial or embedded youtube video

**Describe alternatives you've considered**

**Additional context**

**Comment by TRtomasz** [comment]
I'm reopening this as there is no placeholder displayed. tested on new account

**Comment by TRtomasz** [comment]
By no data i mean following situation.
1. User has no active campaigns
2. User has no active ad slots

**Comment by rori4** [comment]
I don't think displaying "no data" is necessary as we are filling the chart with the dates and 0 values if there is no data present. This way users can see what is the time period when they choose hour/day/week

@Ivshti What do you think about this?

**Comment by TRtomasz** [comment]
As a reminder, my initial idea was to display links/previews of tutorials or youtube video(if there is any) to make users onboarding easier.

**Comment by rori4** [comment]
This with the tutorials is implemented now with the getting started guide and waits for the PR to be merged. We decided to have it like that in this issue -> UX: getting started guide #79

And yes, the chart can be hidden if there are no campaigns (ever) and no ad slots (ever) and not only active as you might want to see previous performance on weekly time frame for example.

Does this sound good?

**Comment by TRtomasz** [comment]
I see, yes i think #79 also fix this issue, then i guess it is not needed to hide charts

**Comment by rori4** [comment]
Ok so I will close this in favor of #79
