### ISSUE TITLE
When passback is set for an ad slot creation ends with an error

### ISSUE THREAD

**Issue by TRtomasz** [AdExNetwork/adex-platform#257]
**Describe the bug**
It is not possible to set passback for an ad slot because it results in backend error

**To Reproduce**
1. Log in as a publisher
2. Click Ad slots
3. Click create new ad slot button
4. Set passback with image and url
5. Try to save adslot
6. Error is displayed
**Expected behavior**
It should be possible to  create an ad slot with a passback
**Screenshots**
![image](https://user-images.githubusercontent.com/40594253/70233546-b5074400-1756-11ea-9186-bbb3d41ab38d.png)

**Desktop (please complete the following information):**
Firefox windows 10
**Smartphone (please complete the following information):**

**Additional context**

**Comment by rori4** [comment]
This was fixed yesterday and should be deployed on staging right now
