### ISSUE TITLE
Dropdowns should displayed under buttons that are used to open them

### ISSUE THREAD

**Issue by TRtomasz** [AdExNetwork/adex-platform#258]
**Is your feature request related to a problem? Please describe.**
When opening a dropdown it usually is displayed over a button so it might not be clear what we are selecting

**Describe the solution you'd like**
Dropdowns should be displayed under buttons: Screenshots examples
![image](https://user-images.githubusercontent.com/40594253/70233658-eb44c380-1756-11ea-980f-8dcc67bf5538.png)
![image](https://user-images.githubusercontent.com/40594253/70233687-f992df80-1756-11ea-8da9-a05ca9657a51.png)
![image](https://user-images.githubusercontent.com/40594253/70233764-1deebc00-1757-11ea-9885-3e3a829771e5.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by ivopaunov** [comment]
It's fixed.
