### ISSUE TITLE
Need  to make Campaign State tab in campaign view more user friendly

### ISSUE THREAD

**Issue by dmngdsm** [AdExNetwork/adex-platform#260]
Right now all the users see is some random DAI and addresses. We need to make this more understandable if it will be user-facing information.

 
![Screenshot 2019-12-05 at 14 36 38](https://user-images.githubusercontent.com/15030734/70239830-b8112d00-1774-11ea-9f2f-85c813c2bf4a.png)

**Comment by rori4** [comment]
Any suggestions how we can make this more user friendly? The DAI on top is that how much the address below has earned. Any suggestions would be appreciated.

**Comment by Ivshti** [comment]
First suggestion: make it a table that's divied into categories: "DAI earned, Ethereum address"

Later on we can just remove this and replace it by #211
