### ISSUE TITLE
Add Tooltips on Campaign Statuses

### ISSUE THREAD

**Issue by dmngdsm** [AdExNetwork/adex-platform#261]
**Is your feature request related to a problem? Please describe.**
Some users don't understand the current campaign statuses such as Withdraw, Exhausted, etc.

**Describe the solution you'd like**
Add tooltips next to the Campaign Status under Campaigns in the Dashboard

**Comment by rori4** [comment]
I will add this as I am working on the tables currently

**Comment by Ivshti** [comment]
closing in favor of https://github.com/AdExNetwork/adex-platform/issues/184
