### ISSUE TITLE
Rearrange steps order when adding new ad unit

### ISSUE THREAD

**Issue by dmngdsm** [AdExNetwork/adex-platform#262]
**Is your feature request related to a problem? Please describe.**
I've been using the platform as an advertiser for some time and found something that I think can be optimized. 

Right now the steps to add an ad unit are:

**General info --> upload creative --> set audiences --> preview --> done**

Often I just want to see if there's a certain targeting option or just play around with audiences, but every time I just want to check this I first have to upload a creative which is frustrating.

I suggest the order to be rearanged to:

**General info --> set audiences  -->upload creative --> preview --> done**

Asked @IvoPaunov  and he said that it should be easy to implement

**Comment by rori4** [comment]
We need first to set the image and then set the targeting as this is how the google vision branch works. Please don’t change this!
