### ISSUE TITLE
Terminology/nomenclature in the platform

### ISSUE THREAD

**Issue by vanina-iv** [AdExNetwork/adex-platform#268]
Opening this issue to improve the terminology we use in the platform. Please add your suggestions. 

---
| **Current**  | **Suggested** |
| ------------- | ------------- |
| Identity  | Account ID  |
| Identity ethereum address  | Account ID  |
| Identity balance  | Account balance  |
| On identity  | Available balance  |
| On channels  | In campaigns  |
| Deposit amount  | Campaign budget  |

**Comment by Ivshti** [comment]
This is a dramatic improvement. Great job!

**Comment by rori4** [comment]
For this should we also change all translation variables that mention those above? @IvoPaunov @Ivshti

**Comment by rori4** [comment]
On identity | Available balance
-- | --

This should be discussed as it is not entirely correct. The total available balance is the one on channels and the one on the identity.

I suggest changing this to 

On identity | In Account
-- | --

**Comment by Ivshti** [comment]
@rori4 in this case we will drop "On identity" altogether, and maybe show it only in the Accounts page (or not show it at all)

**Comment by Ivshti** [comment]
seemsto be done in staging
