### ISSUE TITLE
weird blue rectangle around the chat button

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-platform#269]
![bluething2](https://user-images.githubusercontent.com/1247629/71181906-faeefc80-226c-11ea-98ad-98ed4456f933.png)
**Describe the bug**
There's a weird semi-transparent blue rectangle in the bottom left around the chat button

**To Reproduce**
Open platform.adex.network on chromium

**Comment by rori4** [comment]
I can't reproduce it with Chromium Version 74.0.3729.131 (Official Build) (64-bit)

**Comment by rori4** [comment]
@Ivshti Have you tried selecting something before this appeared? If you click somewhere on screen does it disappear?

**Comment by rori4** [comment]
I was able to reproduce it if I double click fast on the background which selects the Iframe
