### ISSUE TITLE
"Top up" page

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-platform#279]
**Is your feature request related to a problem? Please describe.**
We don't really encourage topping up the account right now.

**Describe the solution you'd like**
Add a separate "top up" page that's clearly showing:
- a big button to top up with GBP (leads to the ramp widget)
- the ETH address (Identity address) of the account labelled "DAI deposit address"; in the future, with [stablecoin agnostic UX](https://github.com/AdExNetwork/aips/issues/20), it'd be "USDC/DAI deposit address"; there should be a tooltip next to that explaining that you can send tokens from exchanges too 
- in the future, there'd be a button to top up with BTC as well, so include that in the design; actually, to keep the page from being too empty, include it as well, with a label "coming soon"

Use a card-like design for the buttons (or use cards), because they need to contain additional information within them - e.g. that only Revolut is supported right now (in the future, fees too)

On the left navbar, the "Top up" button should be right on top of "Account". Also re-order a bit: the order should be: Top up, Account, Help. "Transactions" should be moved to the top right dropdown AND the Account page

**Additional context**

- [ ] if you try to open a campaign but your balance is 0, ask if you want to top up and then go to the Top up page

**Comment by alesinka** [comment]
Here is an initial mockup:
![TOP UP](https://user-images.githubusercontent.com/24762344/72252409-e00f6e00-3607-11ea-9fb3-f76621bbcce5.jpg)

**Comment by ivopaunov** [comment]
Nice, just without the border radius :) I like the advertiser/publisher tabs but maybe with little margin at the bottom.

**Comment by alesinka** [comment]
![TOP UP](https://user-images.githubusercontent.com/24762344/72253444-3e3d5080-360a-11ea-9337-8d2ce8c6aaee.jpg)

**Comment by rori4** [comment]
Perhaps we should use not GBP but 'Deposit with Credit Card' or something like that
