### ISSUE TITLE
evaluate walletconnect

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-platform#35]
https://walletconnect.org/

is this useful for us?

**Comment by rori4** [comment]
are we going to implement this to the platform? it is useful for sure since we have it on staking as well but I think it will be better if we use something like -> https://github.com/Web3Modal/web3modal however I don't thinkj this will work with ethersjs

**Comment by Ivshti** [comment]
Not doing it

Problems:

- no user demand for it
- wonky implementations of WalletConnect across wallets
- web3modal doesn't play well with ethersjs as mentioned

It's more acceptable for the staking portal which is simpler and targeted towards slightly more technical users
