### ISSUE TITLE
export of receipts (statements/reports) of campaign spend/earnings

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-platform#37]
this report should work for both sides (advertiser/publisher)

- [x] For the advertiser, it should be per-campaign, with a breakdown of the spend by website

- [x] For the publisher, it should be time-based, with a total aggregate of how much they earned

it can be used for accounting purposes in most jurisdictions; unfortunately it probably won't be as good as having an invoice, but it's something

**Comment by rori4** [comment]
this is related to Campaign statistics: spend breakdown #211

**Comment by rori4** [comment]
@Ivshti What did we decide on the publisher reports. We discussed that we can get the data by month. What was the endpoint for that?

**Comment by Ivshti** [comment]
It's the regular analytics, however with a channelid query parameter to filter it only for the channel, and obviously `for-publisher`

You can get it by day, by month, etc. I recommend day
