### ISSUE TITLE
UX issue: advertiser/publisher switch UX is suboptimal

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-platform#49]
Suggestion: make it more noticable and tab-like; e.g. "[Publisher][Advertiser]"

**Comment by Ivshti** [comment]
closing this in favour of https://github.com/AdExNetwork/adex-dapp/issues/77

**Comment by Ivshti** [comment]
reopening this cause it's still a problem according to https://github.com/AdExNetwork/adex-okrs/issues/2#issuecomment-541491692, and we need a different UX (than a toggle button)

**Comment by alesinka** [comment]
Is this the exact comment related to the issue? "There's apparently no possible verification/interaction between the advertiser and the Publisher."

If yes - what do we want them to see then? How do we want them to interact?

**Comment by Ivshti** [comment]
@alesinka what I'm suggesting is to replace the toggle switch here with tabs
![Screenshot_2020-01-03 AdEx Platform](https://user-images.githubusercontent.com/1247629/71714563-49bc9a80-2e06-11ea-8093-349b1618a521.png)

Instead of just showing "Advertiser <switch>" or "Publisher <switch>" it will show "Advertiser | Publisher" and the currently selected one would be visibly highlighted

**Comment by alesinka** [comment]
Here are two suggestions according to the material components - white and color themed tabs:
![Advertiser tab – 2](https://user-images.githubusercontent.com/24762344/71826214-18fa9080-30a6-11ea-91de-3228a90bbb11.jpg)
![Advertiser tab – 3](https://user-images.githubusercontent.com/24762344/71826215-18fa9080-30a6-11ea-9300-9c558c6fc7fd.jpg)
![Publisher tab – 1](https://user-images.githubusercontent.com/24762344/71826216-19932700-30a6-11ea-8dc5-9832c8aa92d0.jpg)
![Publisher tab – 2](https://user-images.githubusercontent.com/24762344/71826217-19932700-30a6-11ea-9219-0cc3d1fb1a40.jpg)

**Comment by DimoStoyanov** [comment]
We can simply put a background color on the active state: 
<img width="656" alt="Screenshot 2020-02-25 at 13 01 46" src="https://user-images.githubusercontent.com/5999924/75244410-6c4eac80-57d4-11ea-8163-57de7e3c45d7.png">

**Comment by Ivshti** [comment]
@alesinka we decided to reopen this cause it's still not perfectly clear; A background color helps @rori4 please implement
