### ISSUE TITLE
UX: getting started guide

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-platform#79]
we should show a quick and simple getting started guide on the dashboard

publishers:

* create an ad slot
* copy the HTML
* profit

advertisers:

* get your account funded
* create an ad unit
* create your first ad campaign

Each of the steps should automatically get a tick if completed

**Comment by alesinka** [comment]
![Start-Guide](https://user-images.githubusercontent.com/24762344/59260684-b858c180-8c44-11e9-819d-0af900736cf0.jpg)
This is the resulted idea after a discussion with @IvoPaunov . The unicorn is supposed to flash-jump either from the bottom screen together with a notification (as seen on asana app) when completing a task, or as drawn in the image would also work :)

**Comment by vanina-iv** [comment]
Discussed the issue w/ Rangel and Paunov, the proposed Getting started guide is suboptimal. We agreed that @rori4 will look for Joyride alternatives to make sure we select the best possible tool, and we will then implement it on the platform.

**Comment by vanina-iv** [comment]
### Overview

New concept about the **Getting started** guide: We will keep a "ribbon" on top of every page within the platform, until all steps are complete, something like that: 

![GS](https://user-images.githubusercontent.com/8737960/74169859-a9dc0300-4c34-11ea-8daf-4f9d73f8606e.png)

Each step will have a different avatar/badge with Eddie. 

Each step will be clickable, even if it's completed, and the text below the step will change correspondingly. The tutorials will appear in a pop-up (these may be videos or short text tutorials) to keep users in the platform. 

Everyone who completes all steps will be receiving a bonus reward of 5 dai. Ivo will create a script to validate the steps completion, and the script will be checking for the following: 
- No bonus reward received previously
- Confirmed email address
- Valid ad campaign (for advertisers) or 5,000 impressions (for publishers). 

Each account will be eligible for one bonus only, even if the account is used both as a publisher or advertiser. There will be Terms and Conditions applicable, these will be either a pop-up, or in a blogpost (TBD). 

### Steps for Advertisers 
1. Confirm your email address
2. Create an ad unit
3. Fund your account 
4. Launch your first campaign
5. Receive your bonus

### Steps for Publishers 
1. Confirm your email address
2. Create an ad slot
3. Place an ad slot on your site
4. Reach 5,000 impressions for your ad slot(s)
5. Receive your bonus

**Comment by alesinka** [comment]
Here is what we agreed on so far: 
![Getting started ADV](https://user-images.githubusercontent.com/24762344/74435367-f14cd400-4e6c-11ea-809c-6b987a0cc861.jpg)
![Getting started PUB](https://user-images.githubusercontent.com/24762344/74435371-f1e56a80-4e6c-11ea-9bc4-17bb2a957435.jpg)

Also the different states explained:
![image](https://user-images.githubusercontent.com/24762344/74435538-50aae400-4e6d-11ea-9412-0a832c1f0177.png)

**Comment by rori4** [comment]
~This has been blocked by AdExNetwork/adex-relayer#64~
UPDATE: This has been resolved

**Comment by rori4** [comment]
We have decided to hide the bonus step for now as this needs to be done in the relayer: AdExNetwork/adex-relayer#66

**Comment by rori4** [comment]
I think this is completed. I will close it.
