### ISSUE TITLE
Transactions UI can be replaced by a link to Etherscan

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-platform#80]
we don't really need the transactions screen, it can be replaced by alink to etherscan

- [ ] rather than an option in the sidebar, it should be an option in the top right dropdown
- [ ] there should be a dialog warning the user that this is technical information
- [ ] if it’s still counter factual, it should pop up a dialog explaining that and showing the identity information

**Comment by rori4** [comment]
@Ivshti Is this issue still relevant? We have a link to Etherscan on the left side.

**Comment by Ivshti** [comment]
it's done
