### ISSUE TITLE
show USD estimates

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-platform#82]
all summaries that show DAI balances should also show USD estimates:

- [ ] Dashboard: rather than showing "on identity, on channels", show the USD estimate
- [ ] Account: this should show total balance, additionally show on-chain balance and on channels separately, and under each one, there will be an USD estimate
- [ ] when opening campaigns, show a USD estimate of your deposit
- [ ] there should be a toggle to turn USD estimates on/off in the top right dropdown

the USD estimate should just say "xx.x USD (?)"  where "(?)" is a small question mark icon that will be a link to the help section explaining it.

**Comment by rori4** [comment]
How about [https://www.coingecko.com/en/api ](https://www.coingecko.com/en/api) for getting the price of DAI or any other coin we use?

**Comment by Ivshti** [comment]
v5 will use USDT which
1) is named **USD**T, so this will give info to people unfamiliar to stablecoins that it's USD
2) holds it's peg better than dai

so this is not worth doing now
